<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <UseAppHost>false</UseAppHost>
    <LangVersion>preview</LangVersion>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <ReunionPackageVersion Condition="'$(ReunionPackageVersion)' == ''">0.1.0-alpha.1</ReunionPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Reunion" Version="$(ReunionPackageVersion)" />
    <PackageReference Include="Reunion.Errors.Extensions" Version="$(ReunionPackageVersion)" />
  </ItemGroup>

</Project>
